### PR TITLE
changed icon for TIP-admonition to lightbulb

### PR DESCRIPTION
**Pull request by PrimaryFeather**
As discussed in #72, the bitcoin symbol may cause confusion. Using the lightbulb icon is probably a better default.

Thanks in advance!

### CODE REVIEW

**Comment by mojavelinux** [comment]
We need to pick a new color since a green light bulb doesn't make much sense.

**Comment by PrimaryFeather** [comment]
Agreed!

Here is how the current admonition colors look like:

colors

The light bulb probably ought to be yellow, which is already taken by the exclamation sign (`important`). We could make that one green instead (i.e. switch the colors of `tip` and `important`), or maybe pick a whole new combination of colors — whatever you prefer!

I created a JSFiddle so we can play around with the colors easily: https://jsfiddle.net/h3pvad77/1/

**Comment by mojavelinux** [comment]
Thanks for setting up the fiddle!

I fiddled around a bit and here's what I came up with:

admonition-icons

https://jsfiddle.net/hf0g8jyt/2/

I think the colors fit the icons and they all stand out as they should.

**Comment by mojavelinux** [comment]
I updated the PR with the proposal.

**Comment by PrimaryFeather** [comment]
Yes, that's looking excellent! You're right, a black / dark grey lightbulb is probably best, and it's also consistent with `asciidoctor-pdf` then.

If there's anything else I can do to help, just let me know! Thanks again for looking into this! :smile:

**Comment by mojavelinux** [comment]
I'd be interested to hear from @mfitzp or @allenan. If I get :+1: then we'll proceed.

**Comment by mfitzp** [comment]
This looks great to me, nice too that the colours are consistent, thanks.

**Comment by mojavelinux** [comment]
Great! Thanks for the feedback! Let's move forward then.

**Comment by PrimaryFeather** [comment]
That's great! Thanks again for your efforts! :smile:

**Pull request merged**
