### PR TITLE
Enable Kindle huffdic compression

### PR DESCRIPTION
**Pull request by danhyun**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Is it considered a best practice to always have this enabled? Otherwise, it might be best to make it an option that can be passed from the commandline...perhaps something like `ebook-compression=huffdic`. Thoughts?

**Comment by danhyun** [comment]
Yeah, that's actually a better fit for how asciidoc operates on the whole. We should let `ebook-compression` correlate to the 3 different compression modes the `kindlegen` bin has to offer.

**Comment by danhyun** [comment]
Does this mean that there are no tests running for this project?
I would just like to have some tests to run to make sure I'm not breaking anything.
https://github.com/asciidoctor/asciidoctor-epub3/blob/master/Rakefile#L32

**Comment by mojavelinux** [comment]
> Does this mean that there are no tests running for this project?

Unfortunately, that is the case atm. It's a top priority to address this. See #11.

**Comment by mojavelinux** [comment]
I also discovered that we can drastically reduce the size of the mobi by passing this undocumented flag:

```
-dont_append_source
```

This cuts the file size in half. I've enabled it on master. https://github.com/asciidoctor/asciidoctor-epub3/blob/master/lib/asciidoctor-epub3/packager.rb#L463

**Comment by mojavelinux** [comment]
Superseded by #99. I implemented the 3 levels of compression, but used the `ebook-compress` flag instead (to align with `ebook-validate` and `ebook-extract`).

**Pull request closed without merging**
