### PR TITLE
resolves #174 add support for inline TOC

### LINKED ISSUE #174: Feature request: Support for ToC in the output
We're moving from producing Epub from Asciidoc by going through Docbook to producing Epub purely with Asciidoctor (to simplify our tool chain). One of the things we have lost in doing so is a table of contents at the start of the book. We'd like to get that back. You can see an example of our current output here: https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/epub/spring-boot-reference.epub

The ToC does appear in the e-reader (only tested on MacBook at present) in the ToC button in the menu at the top. We'd like to have it at the beginning of the book, too, though.

If we could get a switch (perhaps an attribute that goes in the spine file) to enable that behavior, we'd really appreciate it.

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Comment by craigscott-crascit** [comment]
I can't review the code changes themselves, but I have given the changes a try on my project. I've noticed the following:

* My colophon is being put after the TOC instead of before it.
* The "Table of Contents" heading in the main text has poor spacing, it is very close to the start of the actual TOC. There is also no horizontal rule like for other headers (parts, chapters). The font also looks different to the other headings. See attached screenshots which show these differences.

TableOfContentsHeader

IntroductionHeading

**Comment by slonopotamus** [comment]
Thanks for testing! Do I understand correctly that by colophon you mean preface (in Asciidoctor terminology)? The text that is but between document title and first chapter heading.

Also, does `:outlinelevels:` combined with `:toclevels:` allow you to achieve TOC depth logic that you would like to have?

I'll work on fixing visuals so they match the style of rest of the book before these changes hit `master`.

**Comment by craigscott-crascit** [comment]
No the colophon is a separate section of its own. It typically contains things like a copyright notice, ISBN number, etc. It refers to the content you usually see on the inside cover or first page or so of a book. This text is usually more related to the publisher or printing details of the book. It has its own keyword `colophon` which you place before the section like so:

```asciidoc
[colophon]
= Name Of Book

... copyright notice, ISBN, etc.
```

The preface is different and comes later (typically after the TOC).

**Comment by craigscott-crascit** [comment]
Sorry, forgot to mention. Yes, the `:outlinelevels:` and `:toclevels:` appear to be working correctly. I can have 1 level in the nav and 3 levels in the inlined TOC in the main text. 👍

**Comment by slonopotamus** [comment]
Okay, so we need:
1. Adjust order of TOC relative to other book parts
2. Fix visual formatting

**Comment by slonopotamus** [comment]
Sorry, by "preface" I actually meant "preamble".

**Comment by craigscott-crascit** [comment]
Ah, yes, preamble is probably similar to or the same as colophon.

**Comment by slonopotamus** [comment]
Positioning TOC in other places than "after cover/frontmatter and before first page of book contents" is going to be a separate issue. Note that asciidoctor-pdf [also has such limitation](https://github.com/asciidoctor/asciidoctor-pdf#table-of-contents).

WRT your colophon, you could try using `:epub3-frontmatterdir:` and hand-crafting an html file for it. It won't possibly make you happy because you can't use Asciidoctor markup there though.

**Comment by slonopotamus** [comment]
WRT visual formatting: I suddenly hit w3c/epubcheck#1160. Investigating options to workaround it.

**Comment by mojavelinux** [comment]
> Note that asciidoctor-pdf also has such limitation.

That statement is out of date. It's now possible to place the TOC manually using the toc macro.

**Comment by craigscott-crascit** [comment]
> That statement is out of date. It's now possible to place the TOC manually using the toc macro.

@mojavelinux Is that only on quite recent master of asciidoctor-pdf? I tried doing some quick experiments just now and I get ruby errors with stack traces if I try to place the toc manually with the `toc::[]` macro. I've got asciidoctor-pdf pinned to a relatively recent commit (7e7a5df4476815e83448eae6228ddf466d1ea347) in order to pick up the configurable number of index columns.

FWIW, I get the same error with asciidoctor-epub3 as I do with asciidoctor-pdf when placing the toc manually, but seems expected for epub3 since it isn't yet supported.

**Pull request merged**
