### PR TITLE
resolves #223 set up Rubocop linter

### LINKED ISSUE #223: Set up Rubocop to enforce consistent code style
Set up Rubocop to enforce a consistent code style. The code style should match other projects in the Asciidoctor org. The project that maintains these mos recent set of rules is Asciidoctor PDF. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/.rubocop.yml.

Related commit: https://github.com/asciidoctor/asciidoctor-pdf/commit/f3a10601b217a5aee8a6803f6de97a13baed0b1f

### PR DESCRIPTION
**Pull request by slonopotamus**
Resolves #223

Rubocop config was takes as-is from https://github.com/asciidoctor/asciidoctor-pdf/blob/e80edba41fa724bef5f43ca30028afd873e07317/.rubocop.yml

This PR massively changes inventation of packager.rb and converter.rb, this will cause lots of conflicts in existing PRs. Though, asctiidoctor-pdf went through it, so maybe it's ok.

### CODE REVIEW

**Comment by slonopotamus** [comment]
Hmm... [README says](https://github.com/asciidoctor/asciidoctor-epub3/blob/master/README.adoc#prerequisites) that asciidoctor-epub3 supports Ruby 1.9.3. Is it true? If yes, my changes to `Gemspec` need to be fixed.

**Comment by mojavelinux** [comment]
> Hmm... README says that asciidoctor-epub3 supports Ruby 1.9.3.

No, the README needs to be updated. The minimum Ruby version we're supporting in Asciidoctor now is Ruby 2.3.

**Comment by mojavelinux** [comment]
As a general rule of thumb, I like to include `resolves #xyz` in the PR subject so that it's easy to navigate to the related issue in the PR list. You can also include it in the description as well.

**Comment by mojavelinux** [comment]
Let's just go for it. Better to get this done before we merge all the other PRs.

**Comment by slonopotamus** [comment]
> include resolves #xyz in the PR subject

Okay, will do in future commits.

**Comment by mojavelinux** [comment]
I should also add that I include it in the commit message, which in turn includes it in the PR subject.

When I commit, I tend to use "square and merge". I then add PR in front of the PR number in the subject that GitHub suggests.

These are not hard and fast rules. It's what has worked for me. If you feel strongly about a different approach, feel free to make that case. I want to make sure maintaining the project is comfortable for you.

**Comment by slonopotamus** [comment]
I'm OK with following your workflow.

**Pull request merged**
