### PR TITLE
Include id and role for inline quoting

### PR DESCRIPTION
**Pull request by lulalala**
Based on [`Asciidoctor::Converter::Html5Converter`](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb).

* allowing wrapping with `<span>`
* allowing specifying id
* allowing specifying class via `role`

### CODE REVIEW

**Comment by lulalala** [comment]
@slonopotamus I have the need to style elements with classes, and the html5 converter was what I needed, so I ported this over to here. Could you review please? Thanks!

**Comment by slonopotamus** [comment]
> can we relax the rubocop rule for blocking nested 4 levels of groups

I just moved them to a separate file.

`converter_spec.rb` is not planned to grow much, it is just a place where I put tests that are too few (yet) to be categorized in their own spec. Oherwise, we would end up with almost all test sitting in `converter_spec.rb`!

**Comment by slonopotamus** [comment]
Doesn't pass tests against asciidoctor-1.5.6.

You can reproduce this locally with setting `ASCIIDOCTOR_VERSION` env variable to `1.5.6` and then running `bundle update`. This is [handled by Gemfile](https://github.com/asciidoctor/asciidoctor-epub3/blob/master/Gemfile#L9).

**Comment by slonopotamus** [comment]
Merged, thanks!

**Pull request merged**
