### PR TITLE
feat: :bug: Do not crash if get_enclosing_chapter returns nil

### PR DESCRIPTION
**Pull request by someth2say**
Fixes https://github.com/asciidoctor/asciidoctor-epub3/issues/470

Probably not the best approach, but enough to protect from the crash.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Could we modify `get_enclosing_chapter` so that if it hits the inner document of an AsciiDoc table cell that it continues looking above that? This is related to (but not limited by) the point made in https://github.com/asciidoctor/asciidoctor/issues/4380.

You can find an example of accessing the parent document from a table cell here:

* https://github.com/asciidoctor/asciidoctor/blob/main/lib/asciidoctor/converter/html5.rb#L1355-L1360

**Comment by mojavelinux** [comment]
Please lock gepub to 1.0.15 instead as 1.0.16 is clearly broken.

**Comment by mojavelinux** [comment]
In order for this to be merged, the code needs to find the chapter when starting from an AsciiDoc table cell, not just skip it. Otherwise, the metadata won't be right.

**Comment by slonopotamus** [comment]
I don't see how to fix this without https://github.com/asciidoctor/asciidoctor/issues/4380. See https://github.com/asciidoctor/asciidoctor-epub3/pull/473 for an ugly workaround.

**Comment by slonopotamus** [comment]
WRT gepub issue, see https://github.com/asciidoctor/asciidoctor-epub3/pull/474 and https://github.com/skoji/gepub/pull/140#issuecomment-2106238457

**Pull request closed without merging**
