### PR TITLE
Fix issue with front cover image

### PR DESCRIPTION
**Pull request by amejiarosario**
Fix "ERROR: front cover image not found or readable"

### CODE REVIEW

**Comment by amejiarosario** [comment]
@mojavelinux could you please take a look at this PR? This fixes the issue of not finding the front cover image by expanding the path correctly

**Comment by mojavelinux** [comment]
This should not be necessary. Can you explain your set up more so that I can understand why you are getting this error?

**Comment by mojavelinux** [comment]
In particular, how are you referring to the front cover image?

**Comment by mojavelinux** [comment]
And how are you running asciidoctor-epub3?

**Comment by amejiarosario** [comment]
Yes, the issue is with the front cover image. 

When I ran asciidoctor-epub3 was complaining `ERROR: front cover image not found or readable`. However, in the same error message, the path was correct! So, I noticed that the part checking for the images was using:

```ruby
::File.readable?(::File.join workdir, image_path)
```

while the error message was using `::File.expand_path image_path, workdir` and was returning a valid path

```ruby
warn %(asciidoctor: ERROR: #{::File.basename(doc.attr 'docfile')}: front cover image not found or readable: #{::File.expand_path image_path, workdir})
```

I think is better to use the same function in both places. Seems like `expand_path` does a better job. After this fix, I find all the images without issue.

**Comment by mojavelinux** [comment]
It's not that one works better than the other. One keeps the path relative,
the other makes it absolute. For some reason, the relative path doesn't
work in your case. I'd like to understand why. Can you provide a sample
project that I can use to reproduce?

**Comment by amejiarosario** [comment]
Yes, you can take a look at my repo if you want:

```
git clone https://github.com/amejiarosario/dsa.js-data-structures-and-algorithms-in-javascript.git dsajs
cd dsajs
git checkout experimental
git submodule update --init --recursive
cd book/config
git checkout experimental
bundle install
bundle exec asciidoctor --backend=epub3 --require=asciidoctor-epub3 --require=asciidoctor-diagram --destination-dir=../dist --out-file=dsajs-algorithms-javascript-book.epub ../book.adoc;
```

Then, you will see the error: `asciidoctor: ERROR: book.adoc: front cover image not found or readable: /..../dsajs/book/images/cover-a4.png`

However, the given path is readable! The warn has the right path.

Because `File.expand_path image_path, workdir` resolves it correctly while `File.join workdir, image_path` fails.


<details>
  <summary>bundle exec asciidoctor --backend=epub3 --require=asciidoctor-epub3 ../book.adoc</summary>

```
bundle exec asciidoctor --backend=epub3 --require=asciidoctor-epub3 --require=asciidoctor-diagram --destination-dir=../dist --out-file=dsajs-algorithms-javascript-book.epub ../book.adoc; \

asciidoctor: ERROR: book.adoc: front cover image not found or readable: /Users/admejiar/Code/tmp/ndsa/book/images/cover-a4.png
asciidoctor: WARNING: preface.adoc: invalid reference to unknown local anchor (or valid bibref): Time Complexity Cheatsheet
asciidoctor: WARNING: preface.adoc: invalid reference to unknown local anchor (or valid bibref): Index
asciidoctor: WARNING: part1.adoc: invalid reference to unknown local anchor (or valid bibref): Merge Sort
asciidoctor: WARNING: part1.adoc: invalid reference to unknown local anchor (or valid bibref): Selection Sort
asciidoctor: WARNING: part1.adoc: invalid reference to unknown local anchor (or valid bibref): Algorithmic Toolbox
asciidoctor: WARNING: part1.adoc: invalid reference to unknown local anchor (or valid bibref): Linked List
asciidoctor: WARNING: part1.adoc: invalid reference to unknown local anchor (or valid bibref): linked-list-inserting-beginning
asciidoctor: WARNING: part2.adoc: invalid reference to unknown local anchor (or valid bibref): Graph
asciidoctor: WARNING: part2.adoc: invalid reference to unknown local anchor (or valid bibref): Tree
asciidoctor: WARNING: part2.adoc: invalid reference to unknown local anchor (or valid bibref): Depth-First Search for Binary Tree
asciidoctor: WARNING: part2.adoc: invalid reference to unknown local anchor (or valid bibref): Breadth-First Search for Binary Tree
asciidoctor: WARNING: part2.adoc: invalid reference to unknown local anchor (or valid bibref): Depth-First Search for Binary Tree
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Linked List
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Queue
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Stack
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Queue
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Searching by value
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Stack
asciidoctor: WARNING: part3.adoc: invalid reference to unknown local anchor (or valid bibref): Queue
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Quadratic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Quadratic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Constant
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Quadratic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Constant
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Quadratic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Constant
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Linearithmic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Linearithmic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Linear
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Linearithmic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Linearithmic
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Constant
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): logarithmic-example
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Getting all permutations of a word
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): Getting all permutations of a word
asciidoctor: WARNING: part4.adoc: invalid reference to unknown local anchor (or valid bibref): HashMap
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Constant
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): constant-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Logarithmic
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): logarithmic-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Linear
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): linear-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Linearithmic
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): linearithmic-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Quadratic
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): quadratic-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Cubic
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): cubic-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Exponential
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): exponential-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Factorial
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): factorial-example
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Array
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Singly Linked List
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Doubly Linked List
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Stack
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Queue
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Binary Search Tree
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Self-balancing Binary Search Trees
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): HashMap
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): TreeMap
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): HashSet
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): TreeSet
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Bubble Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Insertion Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Selection Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Merge Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Quicksort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Bubble Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Insertion Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Selection Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Merge Sort
asciidoctor: WARNING: appendix.adoc: invalid reference to unknown local anchor (or valid bibref): Quicksort
```

</details>

**Comment by mojavelinux** [comment]
Thanks, I will have a look at the repository.

This may have to do with the fact that the destination directory is in a parent folder. That may be a case I wasn't considering.

> However, the given path is readable! The warn has the right path.

The warning shows the full path to make it clear to the user where the file is located. Of course, using that path would also work in the packager. But I don't like to make a change without knowing why the change is necessary. These two paths (relative and absolute) are suppose to be resolving to the same location. We need to know why they are not because it could be the sign of a bigger problem.

**Comment by slonopotamus** [comment]
`experimental` branch no longer exists in that repo. Cover page for `book/readme.asc` (this is the main file, as I understand) in `master` branch is properly added to EPUB using `master` branch of asciidoctor-epub3.

I also don't understand how suggested changes would change anything.

@amejiarosario new repro steps are needed.

**Pull request closed without merging**
