### PR TITLE
fix table frame and grid attributes

### LINKED ISSUE #117: parsing table frame and grid attributes
A table's grid and frame attributes are not recognized:

```
[%autowidth, grid=none, frame=none]
|===
| AN    | Aṅguttara Nikāya
| Cv    | Cullavagga
| Dhp   | Dhammapada
|===
```

### PR DESCRIPTION
**Pull request by gambhiro**
Fixes #117.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'd prefer to keep the existing mapping of CSS classes and just add a rule that handles the value "none".

**Comment by mojavelinux** [comment]
I just added support for the none value and kept the other CSS classes the way they were as the stylesheet uses them.

**Comment by gambhiro** [comment]
Thanks, that's more simple. I must have been coding without thinking enough.

**Comment by mojavelinux** [comment]
Thanks! I had no idea I had forgotten about the "none" attribute, so I'm very glad you brought this up.

**Comment by ecarter-isp** [comment]
So, is this supposedly working now?  Because when I build my site I still see the top and bottom frame borders even though I specified "none".

**Pull request merged**
