### PR TITLE
resolves #338 rescale color palette to use darker shades of gray

### LINKED ISSUE #338: Default colors need improvement
Using asciidoctor-epub3 1.5.0.alpha.17

Contrary to the claims in the readme, the colors of the default theme don't always give good results across the different viewing modes. In some cases, text can be completely unreadable. Here's a few observations with the current stylesheet on some apps/devices:

* For best readability, when viewing with white background the main text should ideally be black (0x000000). This is what you will typically see with commercially produced ebooks (as far as I've been able to tell). The current default for asciidoctor-epub3 appears to be 0x333332 instead, which is dark but not as dark as it should be. This was one of the first things a reader noticed on Kindle (text not as dark and clear as other ebooks). I see the same in calibre and iBooks on a mac desktop, so I presume it would be the same everywhere. Since this is likely to be the default/most commonly used viewing mode, it's an important one to give the optimal readability.

* For black background (Night mode), the text in calibre is still quite dark and hard to read. On iBooks, it's a good contrast and doesn't have the same issue, so the problem seems to be reader-specific.

* For sepia dark, on calibre the text color is the same as the background color, so it disappears completely! Again, iBooks is okay for sepia dark.

### PR DESCRIPTION
**Pull request by slonopotamus**
This commit also removes Kindle-specific color adjustments so minor color changes are expected on Kindle

### CODE REVIEW

**Comment by slonopotamus** [comment]
@nscheer could you please test this on your Kindle?

**Comment by nscheer** [comment]
> @nscheer could you please test this on your Kindle?

Yes, gladly. Is there a specific test document I can build or can you provide one?

**Comment by slonopotamus** [comment]
@nscheer Please, see attached archive with before/after Mobi files of the same [sample book](https://github.com/asciidoctor/asciidoctor-epub3/blob/master/data/samples/sample-book.adoc): [shades-of-gray.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4893031/shades-of-gray.zip)
GitHub rejects `*.moby` attachments for some reason.

**Comment by slonopotamus** [comment]
@craigscott-crascit Could you also give this PR a try?

**Comment by mojavelinux** [comment]
I know @cexbrayat is also interested in the color palette being one of the ones who originally reported an issue on this topic.

**Comment by craigscott-crascit** [comment]
Initial results look good, I'm just waiting on feedback from one other device user.

**Comment by nscheer** [comment]
> @nscheer Please, see attached archive with before/after Mobi files of the same [sample book](https://github.com/asciidoctor/asciidoctor-epub3/blob/master/data/samples/sample-book.adoc):
> [shades-of-gray.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4893031/shades-of-gray.zip)
> GitHub rejects `*.moby` attachments for some reason.

Checked both files this morning. On my Kindle Oasis 2020 I'm unable to spot any differences.
Looks good to me!

**Comment by slonopotamus** [comment]
Okay, something has changed.

Before this PR, links (`<a>`) were specified to have the same color as main text. Now, since we've agreed to no longer specify main text color, I also stopped specifying link color. So they became blue (at least in Calibre).

Uh.

**Comment by craigscott-crascit** [comment]
> Initial results look good, I'm just waiting on feedback from one other device user.

That user has also confirmed it looks a lot better for them now on their device. They had previously provided a side-by-side comparison with other commercially produced content which highlighted the problem, but now the differences in darkness of the fonts are only slight.

**Pull request merged**
