### PR TITLE
Naive rspec-based testing infrastructure

### PR DESCRIPTION
**Pull request by slonopotamus**
If/when this gets merged, #218 needs to be adjusted to call `bundle exec rake spec`

This PR definitely goes towards resolving #11, though scope of that issue isn't clear, so I'm not sure it counts as "resolve".

### CODE REVIEW

**Comment by slonopotamus** [comment]
If/when this gets merged, #218 needs to be adjusted to call `bundle exec rake spec`

**Comment by mojavelinux** [comment]
A journey of a thousand miles starts with a single step.

Let's go with it.

**Comment by mojavelinux** [comment]
FYI, this line isn't needed:

```
# -*- coding: utf-8 -*-
```

That's the default in Ruby.

**Comment by slonopotamus** [comment]
Okay, will remove

**Comment by slonopotamus** [comment]
Oh, you already removed that line. If Rubocop was already set up, it would complain about this.

**Comment by slonopotamus** [comment]
@mojavelinux do you know by chance if there's a more Rubyish way to exec Bundler from Ruby other that doing `system`/`popen`/etc?

**Comment by mojavelinux** [comment]
> If Rubocop was already set up, it would complain about this.

Agreed. That's a next step. We're ready for it.

> do you know by chance if there's a more Rubyish way to exec Bundler from Ruby other that doing system/popen/etc?

See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/spec_helper.rb#L298-L314

I strongly recommend cheating off of asciidoctor-pdf, which is where I put a lot of this infrastructure in place.

**Comment by mojavelinux** [comment]
Be very careful when testing a CLI through Bundler as it can produce false results. That's why I made the run_command in asciidoctor-pdf. It should help ensure it behaves normally.

**Comment by slonopotamus** [comment]
> I strongly recommend cheating off of asciidoctor-pdf
I will definitely do.

**Comment by mojavelinux** [comment]
And https://github.com/asciidoctor/asciidoctor-pdf/blob/master/spec/cli_spec.rb

**Pull request merged**
