### PR TITLE
resolves #210 fix deep interdoc xref when using Asciidoctor 2

### LINKED ISSUE #210: large numbers of invalid `reference to unknown anchor` with links that appear to work, albeit poorly formatted
Using asciidoctor-epub3, version 1.5.0.alpha.9:

version string from code:
```
Asciidoctor EPUB3 1.5.0.alpha.9 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```
(I'm using asciidoctor-docker image for rendering)

When I'm rendering the epub for a book project, I get a large number of warnings akin of the type `invalid reference to unknown anchor`. I've tracked them down to specific instances, and in each instance the link appears to be there, and rendered functionally correctly.

The source is public where I'm seeing this:

- https://github.com/heckj/swiftui-notes

This can be reproduced with the following sequence (assuming you have docker available locally):

```
git clone https://github.com/heckj/swiftui-notes
cd swiftui-notes
docker run --rm -v $(pwd):/documents/ --name asciidoc-to-epub3 asciidoctor/docker-asciidoctor asciidoctor-epub3 -v -t -D /documents/output docs/using-combine-book.adoc
```

A sample error:
`asciidoctor: WARNING: coreconcepts.adoc: invalid reference to unknown anchor in reference chapter: reference-map`

The layout of the book follows the recommended format, with the spine being in 'using-combine-book.adoc', although I do have the 'reference' chapter broken up into a number of smaller files pulled together with `include[]` structures.

The internal anchors are using the `[#chaptername-heading]` and referenced with `<<reference.adoc#chaptername-heading>>`. The links in this form render functionally correct, but with a visible text of `[reference#reference-assign]`. If I explicitly add the xreftext to the internal link, it's properly displayed (that is, in the form: `<<reference.adoc#chaptername-heading,LinkName>>` displays correctly as `LinkName`).

I'm not certain if this is a false alarm, related to the poorly constructed default link xreflabels, or something further. I've tried invoking with `--trace` but it doesn't give me any further clues, and I wasn't sure how to debug this further.

Is this a real issue, or an ephemeral one? And if real, are there any suggestions for how to narrow down and identify the issue I'm hitting that is generating the warnings?

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
@slonopotamus I added some tests for this one. As you can see, we're going to need a helper that reduces the plumbing of setting up a book to convert. I tried to do it in memory using strings, but it ended up being too much effort for not enough gain. It's easier to just create a temporary directory with the contents of the book and run the converter on it in the normal way. There may still be room for more unit-like tests for certain behavior.

**Comment by mojavelinux** [comment]
Since this is so critical, I think we should do an alpha.10 release soon. Rather than me to it, perhaps @slonopotamus you would like to try. I'll file an issue to show how I do it. It's mostly handled by Travis now, but you need to kick it off with a commit.

**Comment by slonopotamus** [comment]
@mojavelinux: define "soon", please. [alpha 10 milestone](https://github.com/asciidoctor/asciidoctor-epub3/milestone/10) list a huge amount of work. As I understand, actual plans for alpha 10 are much more humble.

**Comment by mojavelinux** [comment]
I shoved all open issues to alpha.11. We should release what we have in master now using the GitHub Actions flow (to test it). If you want to get the ebook-validate thing in for alpha.10, go for it. But the choice is yours.

**Pull request merged**
